
platform :ios, '9.0'

target 'AIR1912' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AIR1912
  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
  pod 'KBRoundedButton'
  pod 'Hero'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'CodableAlamofire'
  pod 'Kingfisher'
  pod 'SCLAlertView'
  pod 'SkeletonView'
  pod 'LocationPickerViewController'

end
