
platform :ios, '9.0'

use_frameworks!

workspace 'BeaconApp'

def application_pods
  # Comment the next line if you don't want to use dynamic frameworks
   

   # Pods for AIR1912
   pod 'Alamofire'
   pod 'SwiftKeychainWrapper'
   pod 'KBRoundedButton'
   pod 'Hero'
   pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
   pod 'CodableAlamofire'
   pod 'Kingfisher'
   pod 'SCLAlertView'
   pod 'SkeletonView'
   pod 'LocationPickerViewController'
   pod 'Floaty'
   pod 'KeychainAccess'
end

target 'AIR1912' do
  project 'Application/AIR1912.project'
  application_pods

end
